global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheusPiD'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporterPiD' # RPI
    static_configs:
      - targets: ['node_exporterPiD:9100']

  - job_name: 'cadvisorPiD' # Docker containers
    static_configs:
      - targets: ['cadvisorPiD:8080']

  - job_name: 'traefik' # Web traefik
    static_configs:
      - targets: ['traefik:8080']
