global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter' # RPI
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor' # Docker containers
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'traefik' # Web traefik
    static_configs:
      - targets: ['traefik:8080']