services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-react-app
    restart: always
    ports:
      # Mapeamos el puerto 3000 de tu m√°quina al 80 del contenedor
      - "3000:80"